engines:
  rubocop:
    enabled: true
    config: .codeclimate_rubocop.yml
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - lib/**
   - mod/**
   - "**.rb"
exclude_paths:
- spec/**/*
- vendor/**/*
- mod/pdfjs/files/**/*
- mod/wikirate_source/files/**/*
- mod/**/lib/javascript/**/*.js
- test/**/*
- db/**/*
